---
- hosts: Wazuh-manager
  roles:
    - role: ../../roles/wazuh/ansible-wazuh-manager
    - role: ../../roles/wazuh/ansible-filebeat-oss
      filebeat_output_indexer_hosts:
      - "127.0.0.1" # "{{ indexer_network_host }}" #:9200
  vars_files:
    - ./vars/vars-development.yml