---
- hosts: Wazuh-agent
  become: yes
  become_user: root
  roles:
    - ../../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ stack_network_host }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5

  vars_files:
    - ./vars/vars-development.yml