---
- hosts: Wazuh-indexer
  roles:
  - role: ../../roles/wazuh/wazuh-indexer
    perform_installation: false
  become: no

  vars:
    indexer_node_master: true
    instances:           # A certificate will be generated for every node using the name as CN.
      node1:
        name: node-1
        ip: "127.0.0.1"
        role: indexer
  tags:
    - generate-certs
