nodes:
  # Indexer server nodes
  indexer:
    - name: node-1
      ip: 34.201.121.77

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: node-1
      ip: 34.201.121.77

  # Dashboard node
  dashboard:
    - name: node-1
      ip: 34.201.121.77