nodes:
  # Indexer server nodes
  indexer:
    - name: node-1
      ip: 3.91.89.187 # "ec2-3-91-89-187.compute-1.amazonaws.com"

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: node-1
      ip: 3.91.89.187 # "ec2-3-91-89-187.compute-1.amazonaws.com"

  # Dashboard node
  dashboard:
    - name: node-1
      ip: 3.91.89.187 # "ec2-3-91-89-187.compute-1.amazonaws.com"